# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-05 13:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('idForm', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('formName', models.CharField(max_length=100, null=True)),
                ('formConfig', django.contrib.postgres.fields.jsonb.JSONField()),
                ('formThumbnail', models.TextField(blank=True, null=True)),
                ('statusType', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='C', max_length=1)),
                ('isArchived', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantInForm',
            fields=[
                ('idParticipantInForm', models.AutoField(primary_key=True, serialize=False)),
                ('idParticipant', models.CharField(max_length=100)),
                ('dataCollection', django.contrib.postgres.fields.jsonb.JSONField()),
                ('idForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easystudy.Form')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantToken',
            fields=[
                ('idParticipantToken', models.AutoField(primary_key=True, serialize=False)),
                ('idFutureParticipant', models.CharField(default='p000', max_length=100)),
                ('token', models.CharField(max_length=50)),
                ('idForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easystudy.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('idPermission', models.AutoField(primary_key=True, serialize=False)),
                ('permissionType', models.CharField(choices=[('O', 'Owner'), ('R', 'Reader')], default='R', max_length=1)),
                ('idForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easystudy.Form')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set([('username', 'permissionType', 'idForm')]),
        ),
        migrations.AlterUniqueTogether(
            name='participanttoken',
            unique_together=set([('idForm', 'idFutureParticipant')]),
        ),
        migrations.AlterUniqueTogether(
            name='participantinform',
            unique_together=set([('idParticipant', 'idForm')]),
        ),
    ]
