# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easystudy', '0002_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSpecialConfigs',
            fields=[
                ('idFormSpecialConfigs', models.AutoField(primary_key=True, serialize=False)),
                ('scaleExplained', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('idForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_form', to='easystudy.Form')),
                ('idTrialForm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_form_trial', to='easystudy.Form')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='formspecialconfigs',
            unique_together=set([('idForm', 'idTrialForm')]),
        ),
    ]
