# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easystudy', '0003_auto_20170504_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formspecialconfigs',
            name='idForm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='easystudy.Form'),
        ),
        migrations.AlterField(
            model_name='formspecialconfigs',
            name='idTrialForm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='easystudy.Form'),
        ),
    ]
