# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easystudy', '0004_auto_20170504_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='idForm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easystudy.Form'),
        ),
    ]
