# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easystudy', '0005_usernotification_idform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='idForm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
