# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easystudy', '0006_auto_20170507_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='severityLevel',
            field=models.CharField(choices=[('I', 'Info'), ('D', 'Danger'), ('W', 'Warning'), ('S', 'Success')], default='I', max_length=1),
        ),
    ]
